---
# tasks file for node-exporter
- name: "apt-get update"
  apt:
    update_cache: yes
    cache_valid_time: 3600

- name: "Install node-exporter"
  apt:
    name: ['prometheus-node-exporter']
    state: latest

- name: "Output Node-exporter"
  debug:
    msg: "Connect from the Monitoring_Node to http://localhost:9100/metrics"
